###########################################################
# Project setup:
###########################################################
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pioneer"
version = "0.1"
description = "Deep Learning Framework for Application Problems"
authors = [{ name = "Your Name" }]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2",
    "pandas>=2.3",
    "matplotlib>=3.10",
    "networkx>=3.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]


###########################################################
# Formatting setup:
###########################################################
[tool.black]
line-length = 90
skip-string-normalization = false
target-version = ["py310"]

[tool.pylint.main]
py-version = "3.10"
ignore = [
  "venv",
  ".venv",
  "__pycache__",
]

[tool.pylint.messages_control]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "duplicate-code",
  "fixme",
  "too-few-public-methods",
  "E0402",
  "R0902"
]

[tool.pylint.format]
max-line-length = 90
indent-string = "    "

[tool.pylint.naming]
function-naming-style = "snake_case"
method-naming-style = "snake_case"
variable-naming-style = "snake_case"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"

[tool.pylint.design]
max-args = 10
max-locals = 15
max-branches = 12
max-statements = 50
max-returns = 5
max-positional-arguments = 12

[tool.pylint.reports]
reports = false
score = true
